### ISSUE TITLE
Error while starting TediCross

### ISSUE THREAD

**Issue by jelle619** [Suppen/TediCross#18]
Hi. I'm receiving error while trying to start TediCross

```
0 info it worked if it ends with ok
1 verbose cli [ '/usr/local/bin/node', '/usr/local/bin/npm', 'start' ]
2 info using npm@4.6.1
3 info using node@v6.5.0
4 verbose run-script [ 'prestart', 'start', 'poststart' ]
5 info lifecycle tedicross@0.1.0~prestart: tedicross@0.1.0
6 silly lifecycle tedicross@0.1.0~prestart: no script for prestart, continuing
7 info lifecycle tedicross@0.1.0~start: tedicross@0.1.0
8 verbose lifecycle tedicross@0.1.0~start: unsafe-perm in lifecycle true
9 verbose lifecycle tedicross@0.1.0~start: PATH: /usr/local/lib/node_modules/npm/bin/node-gyp-bin:/home/pi/TediCross/node_modules/.bin:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin:/usr/lo$
10 verbose lifecycle tedicross@0.1.0~start: CWD: /home/pi/TediCross
11 silly lifecycle tedicross@0.1.0~start: Args: [ '-c', 'node main.js' ]
12 silly lifecycle tedicross@0.1.0~start: Returned: code: 1  signal: null
13 info lifecycle tedicross@0.1.0~start: Failed to exec start script
14 verbose stack Error: tedicross@0.1.0 start: `node main.js`
14 verbose stack Exit status 1
14 verbose stack     at EventEmitter.<anonymous> (/usr/local/lib/node_modules/npm/lib/utils/lifecycle.js:279:16)
14 verbose stack     at emitTwo (events.js:106:13)
14 verbose stack     at EventEmitter.emit (events.js:191:7)
14 verbose stack     at ChildProcess.<anonymous> (/usr/local/lib/node_modules/npm/lib/utils/spawn.js:40:14)
14 verbose stack     at emitTwo (events.js:106:13)
14 verbose stack     at ChildProcess.emit (events.js:191:7)
14 verbose stack     at maybeClose (internal/child_process.js:877:16)
14 verbose stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:226:5)
15 verbose pkgid tedicross@0.1.0
16 verbose cwd /home/pi/TediCross
17 verbose Linux 4.4.50+
18 verbose argv "/usr/local/bin/node" "/usr/local/bin/npm" "start"
19 verbose node v6.5.0
20 verbose npm  v4.6.1
21 error code ELIFECYCLE
22 error errno 1
23 error tedicross@0.1.0 start: `node main.js`
23 error Exit status 1
24 error Failed at the tedicross@0.1.0 start script.
24 error This is probably not a problem with npm. There is likely additional logging output above.
25 verbose exit [ 1, true ]
```

UPDATE: Got it working!

**Comment by jelle619** [comment]
I got it working, no assistance needed!

**Comment by Suppen** [comment]
May I ask what the problem was?

**Comment by jelle619** [comment]
I copied the settings from example_settings.json to settings.js on accident.
