### ISSUE TITLE
Massive spam of stacktrace

### ISSUE THREAD

**Issue by aleksandervines** [Suppen/TediCross#28]
I just started up a bot that has been down for a few days. Though minimal activity has been in the channels since.

Perhaps I used an old settings.json file on a new version, or a new version of node, I'm not sure.

I'm using the master version of TediCross, with tag e6fa5ff. And node v6.11.3

The relaying is working, BUT it is producing massive amount of error messages, like 10+ a second. where all are exactly the same as this:

2017-09-19 13:51:07 [ERR]       Couldn't fetch Telegram messages. Reason: Error: Conflict: terminated by other long poll or webhook
    at IncomingMessage.res.on.e (node_modules/teleapiwrapper/lib/bot_api.js:716:18)
    at emitNone (events.js:91:20)
    at IncomingMessage.emit (events.js:185:7)
    at endReadableNT (_stream_readable.js:974:12)
    at _combinedTickCallback (internal/process/next_tick.js:80:11)
    at process._tickCallback (internal/process/next_tick.js:104:9)

Any thoughts to what could have gone wrong?

**Comment by Suppen** [comment]
Your Telegram bot token is in use by another bot, or someone/something has set a webhook for it. Maybe you have two instances of the bot running? Have you shared your token with anyone else? Or used it for another bot?

You should talk to [@Botfather](https://t.me/BotFather) to generate a new token, and then go to the URL https://api.telegram.org/botTOKEN/deleteWebhook (with TOKEN substituted with your new token) to clear any webhooks
