### ISSUE TITLE
TypeError: Cannot read property 'replace' of undefined

### ISSUE THREAD

**Issue by amirnilchi2017** [Suppen/TediCross#33]
C:\Users\Administrator\Desktop\TediCross-master\TediCross-master\lib\discord2telegram\md2html.js:85
          .replace(/</g, "&lt;")
          ^

TypeError: Cannot read property 'replace' of undefined
    at md2html (C:\Users\Administrator\Desktop\TediCross-master\TediCross-master\lib\discord2telegram\md2html.js:85:4)
    at message.embeds.forEach (C:\Users\Administrator\Desktop\TediCross-master\TediCross-master\lib\discord2telegram\setup.js:86:85)
    at Array.forEach (native)
    at Client.dcBot.on (C:\Users\Administrator\Desktop\TediCross-master\TediCross-master\lib\discord2telegram\setup.js:84:20)
    at emitOne (events.js:96:13)
    at Client.emit (events.js:188:7)
    at MessageCreateHandler.handle (C:\Users\Administrator\Desktop\TediCross-master\TediCross-master\node_modules\discord.js\src\client\websocket\packets\handlers\MessageCreate.js:9:34)
    at WebSocketPacketManager.handle (C:\Users\Administrator\Desktop\TediCross-master\TediCross-master\node_modules\discord.js\src\client\websocket\packets\WebSocketPacketManager.js:103:65)
    at WebSocketConnection.onPacket (C:\Users\Administrator\Desktop\TediCross-master\TediCross-master\node_modules\discord.js\src\client\websocket\WebSocketConnection.js:330:35)
    at WebSocketConnection.onMessage (C:\Users\Administrator\Desktop\TediCross-master\TediCross-master\node_modules\discord.js\src\client\websocket\WebSocketConnection.js:293:17)

**Comment by amirnilchi2017** [comment]
anybody knows how can I fix this this Error?
I used markdown text in discord and I got this Error for forwarding it to telegram

**Comment by Suppen** [comment]
Could you share the message giving you this error?

**Comment by amirnilchi2017** [comment]
yes of course
this is the message that bot give me Error for forward it to telegram :
http://uupload.ir/files/xfj4_sshot-1.png

**Comment by Suppen** [comment]
An embed... Those may be buggy, as I haven't tested them much. Will see what I can do

**Comment by amirnilchi2017** [comment]
If the bot can just forward the texts into telegram then it will be great

**Comment by Suppen** [comment]
Is it possible for me to add this bot to my test channel and have it send me such messages?

**Comment by amirnilchi2017** [comment]
yes of course
just type `help` to print the command
here is the join bot Link :
[https://discordapp.com/oauth2/authorize?&client_id=371254809392840704&scope=bot&permissions=1](url)

**Comment by amirnilchi2017** [comment]
So when can you fix this issue??
I really need this bot

**Comment by Suppen** [comment]
Hopefully fixed it now. Currently testing it for compatibility with other embed messages.

I pushed it to branch iss33, commit 8eb995f9659bdce6a7e9ffb7cdb34d5c1d129a33. If you're not very familiar with git, just replace the file `lib/discord2telegram/setup.js` with [this file](https://raw.githubusercontent.com/Suppen/TediCross/8eb995f9659bdce6a7e9ffb7cdb34d5c1d129a33/lib/discord2telegram/setup.js) (right click -> save as)

Will merge to master branch when testing is finished

**Comment by amirnilchi2017** [comment]
Thanks for your help
But one more thing
Can I use this bot to forward discord messages into telegram channel instead of group or super group?

**Comment by Suppen** [comment]
I have now merged the fix into the master branch.

Currently the bot is enforcing integer chat IDs, but channels have names. I made a separate issue on this: https://github.com/Suppen/TediCross/issues/34
