### ISSUE TITLE
Unable to Edit messages from Telegram to Discord

### ISSUE THREAD

**Issue by DragonFlayer** [Suppen/TediCross#35]
```
2017-11-17 17:04:30 [ERR]       Could not edit Discord message: ReferenceError: message is not defined
    at dcBot.ready.then.then.then (D:\Apps\TediCross\lib\telegram2discord\setup.js:279:50)
    at process._tickCallback (internal/process/next_tick.js:109:7)
2017-11-17 17:06:26 [ERR]       Could not edit Discord message: ReferenceError: message is not defined
    at dcBot.ready.then.then.then (D:\Apps\TediCross\lib\telegram2discord\setup.js:279:50)
    at process._tickCallback (internal/process/next_tick.js:109:7)
```

When attempting to edit messages from Telegram to Discord, this error shows up
Messages edited from Discord to Telegram work properly without throwing an error message

**Comment by Suppen** [comment]
This should now be fixed in commit 5d42f3b4c276727ceba16cad013399d69c0f92c3
